version: '3'

services:
  app:
    image: node:20.15.0-bullseye
    container_name: dc-frontend
    command: npm run serve
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    ports:
      - 3000:3000
